language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install qtdeclarative5-dev qt5-default



script:
  - qmake qmake-gtest.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*googletest.*" -E ".*moc_.*"

notifications:
email: false
