#############################################################################
# Makefile for building: lifeQT.app/Contents/MacOS/lifeQT
# Generated by qmake (3.1) (Qt 5.11.0)
# Project:  lifeQT.pro
# Template: app
# Command: /Users/dns/Qt1/5.11.0/clang_64/bin/qmake -o Makefile lifeQT.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers -I../../Qt1/5.11.0/clang_64/lib/QtGui.framework/Headers -I../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt1/5.11.0/clang_64/mkspecs/macx-clang -F/Users/dns/Qt1/5.11.0/clang_64/lib
QMAKE         = /Users/dns/Qt1/5.11.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/dns/Qt1/5.11.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/dns/Qt1/5.11.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = lifeQT1.0.0
DISTDIR = /Users/dns/Desktop/lifeQT\ (1)/.tmp/lifeQT1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/dns/Qt1/5.11.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/dns/Qt1/5.11.0/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		liferect.cpp moc_widget.cpp
OBJECTS       = main.o \
		widget.o \
		liferect.o \
		moc_widget.o
DIST          = android/AndroidManifest.xml \
		android/gradle/wrapper/gradle-wrapper.jar \
		android/gradlew \
		android/res/values/libs.xml \
		android/build.gradle \
		android/gradle/wrapper/gradle-wrapper.properties \
		android/gradlew.bat \
		../../Qt1/5.11.0/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/qdevice.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/features/device_config.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/unix.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/mac.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/macx.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/sanitize.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/clang.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/qconfig.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/qt_config.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/spec_post.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/toolchain.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/default_pre.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/default_post.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/warn_on.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/qt.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/resources.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/moc.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/uic.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/file_copies.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/exceptions.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/yacc.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/lex.prf \
		lifeQT.pro widget.h \
		liferect.h main.cpp \
		widget.cpp \
		liferect.cpp
QMAKE_TARGET  = lifeQT
DESTDIR       = 
TARGET        = lifeQT.app/Contents/MacOS/lifeQT

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_widget.h $(OBJECTS)  
	@test -d lifeQT.app/Contents/MacOS/ || mkdir -p lifeQT.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: lifeQT.pro ../../Qt1/5.11.0/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt1/5.11.0/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/qdevice.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/features/device_config.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/unix.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/mac.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/macx.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/sanitize.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/clang.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/qconfig.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt1/5.11.0/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/qt_config.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/spec_post.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/toolchain.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/default_pre.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/default_post.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/warn_on.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/qt.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/resources.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/moc.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/uic.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/file_copies.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/exceptions.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/yacc.prf \
		../../Qt1/5.11.0/clang_64/mkspecs/features/lex.prf \
		lifeQT.pro \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt1/5.11.0/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile lifeQT.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../Qt1/5.11.0/clang_64/mkspecs/features/spec_pre.prf:
../../Qt1/5.11.0/clang_64/mkspecs/qdevice.pri:
../../Qt1/5.11.0/clang_64/mkspecs/features/device_config.prf:
../../Qt1/5.11.0/clang_64/mkspecs/common/unix.conf:
../../Qt1/5.11.0/clang_64/mkspecs/common/mac.conf:
../../Qt1/5.11.0/clang_64/mkspecs/common/macx.conf:
../../Qt1/5.11.0/clang_64/mkspecs/common/sanitize.conf:
../../Qt1/5.11.0/clang_64/mkspecs/common/gcc-base.conf:
../../Qt1/5.11.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt1/5.11.0/clang_64/mkspecs/common/clang.conf:
../../Qt1/5.11.0/clang_64/mkspecs/common/clang-mac.conf:
../../Qt1/5.11.0/clang_64/mkspecs/qconfig.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt1/5.11.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt1/5.11.0/clang_64/mkspecs/features/qt_functions.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/qt_config.prf:
../../Qt1/5.11.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt1/5.11.0/clang_64/mkspecs/features/spec_post.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/toolchain.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/default_pre.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/resolve_config.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/default_post.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/qml_debug.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/mac/mac.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/warn_on.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/qt.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/resources.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/moc.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/uic.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/unix/thread.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/qmake_use.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/file_copies.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/mac/rez.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/exceptions.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/yacc.prf:
../../Qt1/5.11.0/clang_64/mkspecs/features/lex.prf:
lifeQT.pro:
../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt1/5.11.0/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt1/5.11.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile lifeQT.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

lifeQT.app/Contents/PkgInfo: 
	@test -d lifeQT.app/Contents || mkdir -p lifeQT.app/Contents
	@$(DEL_FILE) lifeQT.app/Contents/PkgInfo
	@echo "APPL????" > lifeQT.app/Contents/PkgInfo
lifeQT.app/Contents/Resources/empty.lproj: 
	@test -d lifeQT.app/Contents/Resources || mkdir -p lifeQT.app/Contents/Resources
	@touch lifeQT.app/Contents/Resources/empty.lproj
	
lifeQT.app/Contents/Info.plist: 
	@test -d lifeQT.app/Contents || mkdir -p lifeQT.app/Contents
	@$(DEL_FILE) lifeQT.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.lifeQT,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.lifeQT,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.11,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,lifeQT,g" -e "s,@LIBRARY@,lifeQT,g" -e "s,\$${EXECUTABLE_NAME},lifeQT,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../Qt1/5.11.0/clang_64/mkspecs/macx-clang/Info.plist.app >lifeQT.app/Contents/Info.plist

all: Makefile \
		lifeQT.app/Contents/PkgInfo \
		lifeQT.app/Contents/Resources/empty.lproj \
		lifeQT.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt1/5.11.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.h liferect.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp widget.cpp liferect.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r lifeQT.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt1/5.11.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -dM -E -o moc_predefs.h ../../Qt1/5.11.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp
moc_widget.cpp: ../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		liferect.h \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		widget.h \
		moc_predefs.h \
		../../Qt1/5.11.0/clang_64/bin/moc
	/Users/dns/Qt1/5.11.0/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/dns/Qt1/5.11.0/clang_64/mkspecs/macx-clang -I'/Users/dns/Desktop/lifeQT (1)' -I/Users/dns/Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/dns/Qt1/5.11.0/clang_64/lib/QtGui.framework/Headers -I/Users/dns/Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/dns/Qt1/5.11.0/clang_64/lib widget.h -o moc_widget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui \
		../../Qt1/5.11.0/clang_64/bin/uic
	/Users/dns/Qt1/5.11.0/clang_64/bin/uic widget.ui -o ui_widget.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp widget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		liferect.h \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/QApplication
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		liferect.h \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

liferect.o: liferect.cpp liferect.h \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt1/5.11.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../Qt1/5.11.0/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o liferect.o liferect.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

